---
  {{- if .Capabilities.APIVersions.Has "admissionregistration.k8s.io/v1" }}
apiVersion: admissionregistration.k8s.io/v1
  {{- else }}
apiVersion: admissionregistration.k8s.io/v1beta1
  {{- end }}
kind: MutatingWebhookConfiguration
metadata:
  name: {{ .Values.appname }}-webhook-cfg
  namespace: {{ .Values.namespace }}
  annotations:
    cert-manager.io/inject-ca-from: {{ .Values.namespace }}/{{ .Values.appname }}-certificate
webhooks:
  - clientConfig:
      service:
        name: {{ .Values.appname }}
        namespace: {{ .Values.namespace }}
        path: /mutate
    failurePolicy: Fail
    {{- if .Capabilities.APIVersions.Has "admissionregistration.k8s.io/v1" }}
    admissionReviewVersions: ["v1", "v1beta1"]
    sideEffects: None
    {{- end}}
    name: {{ .Values.appname }}.sfdc.internal
    namespaceSelector:
      matchExpressions:
        - key: sidecar-injection
          operator: NotIn
          values: ["disabled"]
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
        resources:
          - pods
